# Generated by Django 3.1.5 on 2021-04-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='object_id',
            field=models.IntegerField(default=0),
        ),
    ]
