# Generated by Django 3.1.5 on 2021-04-28 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_border'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='border',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.border'),
            preserve_default=False,
        ),
    ]
