# Generated by Django 3.1.5 on 2021-04-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_border'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pantarea',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='pantheight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='pantwidth',
            field=models.IntegerField(default=0),
        ),
    ]
