# Generated by Django 2.0 on 2021-03-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranimage', '0002_auto_20210311_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferimage',
            name='avatar',
            field=models.FileField(upload_to='img/avatar/'),
        ),
        migrations.AlterField(
            model_name='transferimage',
            name='content_photo',
            field=models.FileField(upload_to='img/content/'),
        ),
        migrations.AlterField(
            model_name='transferimage',
            name='output_photo',
            field=models.FileField(upload_to='img/output/'),
        ),
        migrations.AlterField(
            model_name='transferimage',
            name='style_photo',
            field=models.FileField(upload_to='img/style/'),
        ),
    ]
