# Generated by Django 3.1.5 on 2021-03-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranimage', '0003_auto_20210311_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferimage',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='transferimage',
            name='content_photo',
            field=models.ImageField(upload_to='img/content/'),
        ),
        migrations.AlterField(
            model_name='transferimage',
            name='output_photo',
            field=models.ImageField(upload_to='img/output/'),
        ),
        migrations.AlterField(
            model_name='transferimage',
            name='style_photo',
            field=models.ImageField(upload_to='img/style/'),
        ),
    ]
