# Generated by Django 3.1.5 on 2021-03-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranimage', '0004_auto_20210316_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferimage',
            name='output_photo',
            field=models.CharField(max_length=100),
        ),
    ]
