# Generated by Django 3.1.5 on 2021-04-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranimage', '0006_auto_20210326_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferimage',
            old_name='like_num',
            new_name='num_steps',
        ),
        migrations.AddField(
            model_name='transferimage',
            name='style_weight',
            field=models.IntegerField(default=0),
        ),
    ]
